format = """
[|](bg:black fg:bold yellow)$username\
${custom.at_path}\
$directory\
$elixir\
$rust\
$git_branch\
$shell\
$gradle
[└─>](bg:black fg:bold yellow)$character
"""

[username]
style_user = 'bg:black fg:yellow'
format = "[$user]($style)"
show_always = true

[directory]
style = 'bg:black fg:purple'
format = '[$path]($style)'

[gradle]
disabled = false
format = ' '

[elixir]
style = 'bg:black fg:bold red'
format = '[ ~ via ($version \(OTP $otp_version\) )]($style)'

[shell]
bash_indicator = '\[BASH\]'
style = 'bg:black fg:white'
format = '[ with $indicator]($style) '
disabled = false

[git_branch]
symbol = '⎇'
style = 'bg:black fg:green bold'
format = '[on $symbol $branch]($style)'

[custom.at_path]
when = true
style = 'bg:black'
format = '[@]($style)'

